blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/SreeshM18/Campusbite/discussions
    about: Ask questions, share ideas, and connect with other developers and contributors.
